/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component UIExpansionPanel
     * @description A custom web component that provides an expandable/collapsible panel.
     * The panel consists of a header and a details section. The details section can be expanded or collapsed by clicking on the header.
     */
    interface UiExpansionPanel {
        /**
          * Indicates whether the panel is expanded or collapsed.
          * @type {boolean}
          * @default false
         */
        "expanded": boolean;
    }
}
declare global {
    /**
     * @component UIExpansionPanel
     * @description A custom web component that provides an expandable/collapsible panel.
     * The panel consists of a header and a details section. The details section can be expanded or collapsed by clicking on the header.
     */
    interface HTMLUiExpansionPanelElement extends Components.UiExpansionPanel, HTMLStencilElement {
    }
    var HTMLUiExpansionPanelElement: {
        prototype: HTMLUiExpansionPanelElement;
        new (): HTMLUiExpansionPanelElement;
    };
    interface HTMLElementTagNameMap {
        "ui-expansion-panel": HTMLUiExpansionPanelElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component UIExpansionPanel
     * @description A custom web component that provides an expandable/collapsible panel.
     * The panel consists of a header and a details section. The details section can be expanded or collapsed by clicking on the header.
     */
    interface UiExpansionPanel {
        /**
          * Indicates whether the panel is expanded or collapsed.
          * @type {boolean}
          * @default false
         */
        "expanded"?: boolean;
    }
    interface IntrinsicElements {
        "ui-expansion-panel": UiExpansionPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component UIExpansionPanel
             * @description A custom web component that provides an expandable/collapsible panel.
             * The panel consists of a header and a details section. The details section can be expanded or collapsed by clicking on the header.
             */
            "ui-expansion-panel": LocalJSX.UiExpansionPanel & JSXBase.HTMLAttributes<HTMLUiExpansionPanelElement>;
        }
    }
}
